global:
  # Prometheus interroge chaque target toutes les 15 secondes
  scrape_interval: 15s
  # Timeout si une target ne répond pas en 10s
  scrape_timeout: 10s

scrape_configs:
# Job pour notre app Flask
- job_name: 'flask-devops-app'
  static_configs:
  # 'app' = nom du service dans Docker Compose
  # Prometheus peut joindre l'app via ce nom en interne
  - targets: [ 'app:5000' ]
  # La librairie prometheus-flask-exporter expose les métriques
  # sur /metrics par défaut
  metrics_path: /metrics

# Job pour surveiller Prometheus lui-même
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]
