# Bloc obligatoire pour Nginx (configuration globale des workers)
events {
    worker_connections 1024;
}
 
http {
    # 'upstream' = groupe de serveurs vers lesquels on redirige
    # 'app' = nom du service Docker Compose (défini plus loin)
    # ':5000' = port sur lequel Flask écoute
    upstream flask_app {
        server app:5000;
    }
 
    server {
        # Nginx écoute sur le port 80 (HTTP standard)
        listen 80;
 
        # Toutes les requêtes sur / sont proxifiées vers Flask
        location / {
            proxy_pass http://flask_app;
 
            # On transmet des infos utiles à Flask
            # Le nom de domaine demandé par le client
            proxy_set_header Host $host;
            # La vraie IP du client (pas l'IP de Nginx)
            proxy_set_header X-Real-IP $remote_addr;
        }
 
        # IMPORTANT : on bloque l'accès public aux métriques !
        # /metrics contient des infos sensibles sur ton app.
        # Seul Prometheus (en interne) peut y accéder.
        location /metrics {
            deny all;
            return 403;
        }
    }
}
