# Ce fichier indique à Ansible quels serveurs gérer
# et comment s'y connecter.
 
[vps]
# Remplace X.X.X.X par l'IP de ta VM Oracle
X.X.X.X ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_deploy
 
[vps:vars]
ansible_python_interpreter=/usr/bin/python3
